export const NOTIFICATIONS_QUEUE = 'notifications-queue';
export const DISPATCH_NOTIFICATION_JOB = 'dispatch-notification';

export const NOTIFICATION_TYPES = {
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_COMPLETED: 'BOOKING_COMPLETED',
  REVIEW_SESSION_CREATED: 'REVIEW_SESSION_CREATED',
  REVIEW_SUBMITTED: 'REVIEW_SUBMITTED',
  REVIEW_REVEALED: 'REVIEW_REVEALED',
} as const;
