import {
  RemoveAvailabilityHandler,
  SetAvailabilityBulkHandler,
  SetAvailabilityForAllWeekHandler,
  SetAvailabilityHandler,
  SetAvailabilityStatusHandler,
  UpdateAvailabilityHandler,
} from './availability.handlers';
import {
  ApproveBookingCancellationRequestHandler,
  CancelBookingHandler,
  CompleteBookingHandler,
  ConfirmBookingHandler,
  MarkNoShowHandler,
  RejectBookingCancellationRequestHandler,
  RejectBookingHandler,
} from './booking.handlers';
import {
  DeleteGalleryItemHandler,
  PublishGalleryItemHandler,
  ReplaceGalleryHandler,
  ReorderGalleryHandler,
  UnpublishGalleryItemHandler,
  UpdateGalleryItemHandler,
  UploadGalleryItemHandler,
} from './gallery.handlers';
import {
  GetAvailableSlotsHandler,
  GetMyOnboardingStateHandler,
  GetMyProfessionalProfileHandler,
  GetProfessionalDashboardHandler,
  GetNewProfessionalsHandler,
  GetProfessionalAvailabilityHandler,
  GetProfessionalBookingsCalendarHandler,
  GetProfessionalBookingsHandler,
  GetProfessionalGalleryHandler,
  GetProfessionalProfileHandler,
  GetProfessionalRevenueSummaryHandler,
  GetProfessionalServicesHandler,
  GetServiceDetailsHandler,
  GetProfileCompletionHandler,
  GetRecommendedProfessionalsHandler,
  GetTrendingProfessionalsHandler,
  ListBookingCancellationRequestsHandler,
  ListProfessionalsHandler,
  ListServiceCategoriesHandler,
  ListServiceCategoryRequestsHandler,
  SearchProfessionalsHandler,
} from './professional.query.handlers';
import {
  CreateProfessionalProfileHandler,
  PauseBookingsHandler,
  ReactivateProfessionalHandler,
  RejectProfessionalHandler,
  RemoveAvatarHandler,
  ResubmitProfessionalHandler,
  ResumeBookingsHandler,
  SuspendProfessionalHandler,
  ToggleListingHandler,
  UpdateProfessionalProfileHandler,
  UpdateProfessionalSettingsHandler,
  VerifyProfessionalHandler,
} from './profile.handlers';
import {
  ActivateServiceHandler,
  AddServiceHandler,
  ApproveServiceCategoryRequestHandler,
  CreateServiceCategoryHandler,
  CreateServiceCategoryRequestHandler,
  DeactivateServiceHandler,
  DeleteServiceCategoryHandler,
  DeleteServiceHandler,
  RejectServiceCategoryRequestHandler,
  RemoveServiceImageHandler,
  SetServiceCommuneFeeHandler,
  UpdateServiceCategoryHandler,
  UpdateServiceHandler,
  UpsertServicesBulkHandler,
} from './service.handlers';

export const ProfessionalCommandHandlers = [
  CreateProfessionalProfileHandler,
  UpdateProfessionalProfileHandler,
  VerifyProfessionalHandler,
  RejectProfessionalHandler,
  SuspendProfessionalHandler,
  ReactivateProfessionalHandler,
  ToggleListingHandler,
  PauseBookingsHandler,
  ResumeBookingsHandler,
  ResubmitProfessionalHandler,
  UpdateProfessionalSettingsHandler,
  RemoveAvatarHandler,
  CreateServiceCategoryHandler,
  UpdateServiceCategoryHandler,
  DeleteServiceCategoryHandler,
  CreateServiceCategoryRequestHandler,
  ApproveServiceCategoryRequestHandler,
  RejectServiceCategoryRequestHandler,
  AddServiceHandler,
  RemoveServiceImageHandler,
  UpdateServiceHandler,
  DeleteServiceHandler,
  SetServiceCommuneFeeHandler,
  ActivateServiceHandler,
  DeactivateServiceHandler,
  UpsertServicesBulkHandler,
  SetAvailabilityHandler,
  SetAvailabilityBulkHandler,
  UpdateAvailabilityHandler,
  RemoveAvailabilityHandler,
  SetAvailabilityStatusHandler,
  SetAvailabilityForAllWeekHandler,
  UploadGalleryItemHandler,
  UpdateGalleryItemHandler,
  DeleteGalleryItemHandler,
  PublishGalleryItemHandler,
  UnpublishGalleryItemHandler,
  ReorderGalleryHandler,
  ReplaceGalleryHandler,
  ConfirmBookingHandler,
  RejectBookingHandler,
  CompleteBookingHandler,
  CancelBookingHandler,
  ApproveBookingCancellationRequestHandler,
  RejectBookingCancellationRequestHandler,
  MarkNoShowHandler,
];

export const ProfessionalQueryHandlers = [
  GetMyProfessionalProfileHandler,
  GetMyOnboardingStateHandler,
  GetProfessionalDashboardHandler,
  GetProfessionalProfileHandler,
  ListProfessionalsHandler,
  GetProfessionalServicesHandler,
  GetServiceDetailsHandler,
  GetProfessionalAvailabilityHandler,
  GetProfessionalGalleryHandler,
  GetProfessionalBookingsHandler,
  GetProfessionalBookingsCalendarHandler,
  ListBookingCancellationRequestsHandler,
  GetProfileCompletionHandler,
  GetProfessionalRevenueSummaryHandler,
  ListServiceCategoriesHandler,
  ListServiceCategoryRequestsHandler,
  SearchProfessionalsHandler,
  GetRecommendedProfessionalsHandler,
  GetNewProfessionalsHandler,
  GetTrendingProfessionalsHandler,
  GetAvailableSlotsHandler,
];

export * from './availability.handlers';
export * from './booking.handlers';
export * from './gallery.handlers';
export * from './professional.query.handlers';
export * from './profile.handlers';
export * from './service.handlers';
